2017-01-21 11:10:20,742 [main] ERROR [util.LoggerUtils] - java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
The Connection descriptor used by the client was:
192.168.7.200:1521:testbdc

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:261)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:387)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:441)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at util.DataBase.<clinit>(DataBase.java:41)
	at configSelenium.InitCommonParameter.FilterValue(InitCommonParameter.java:413)
	at configSelenium.InitCommonParameter.InitSqlConfigBatchSql(InitCommonParameter.java:319)
	at configSelenium.ConfigSeleniumStart.main(ConfigSeleniumStart.java:66)

2017-01-21 11:10:20,824 [main] ERROR [util.LoggerUtils] - java.lang.RuntimeException: 获取数据库连接失败！
	at util.DataBase.<clinit>(DataBase.java:49)
	at configSelenium.InitCommonParameter.FilterValue(InitCommonParameter.java:413)
	at configSelenium.InitCommonParameter.InitSqlConfigBatchSql(InitCommonParameter.java:319)
	at configSelenium.ConfigSeleniumStart.main(ConfigSeleniumStart.java:66)

