<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
    <line>
      <![CDATA[资料收取 17_16]]>
    </line>
    <line>
      <![CDATA[<br/><img src="D:\work_space\js_de\debug\SeleniumConfig\bin\Debug\SootScreens\2019-04-17\17_16\资料收取 17_16.png"  hight="300" width="300"  onclick="javascript:window.open(this.src);"/>]]>
    </line>
    <line>
      <![CDATA[移交异常！转出校验信息为：
请添加需要登记的不动产单元！ 请添加办件相关申请人！
]]>
    </line>
    <line>
      <![CDATA[业务号：20190417-0005618]]>
    </line>
  </reporter-output>
  <suite name="所有首次登记流程-国有建设用地使用权及房屋所有权（单套）-首次登记-assert" duration-ms="892" started-at="2019-04-17T09:16:55Z" finished-at="2019-04-17T09:16:55Z">
    <groups>
    </groups>
    <test name="断言详情查看" duration-ms="892" started-at="2019-04-17T09:16:55Z" finished-at="2019-04-17T09:16:55Z">
      <class name="Test.DataProviderSet_Assert">
        <test-method status="PASS" signature="insetToExcel()[pri:0, instance:Test.DataProviderSet_Assert@41382722]" name="insetToExcel" is-config="true" duration-ms="710" started-at="2019-04-17T17:16:55Z" finished-at="2019-04-17T17:16:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insetToExcel -->
        <test-method status="FAIL" signature="star(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Test.DataProviderSet_Assert@41382722]" name="star" duration-ms="45" started-at="2019-04-17T17:16:55Z" data-provider="AssertData" finished-at="2019-04-17T17:16:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[申请人信息]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[申请信息]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[申请人信息标题断言]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at Test.DataProviderSet_Assert.star(DataProviderSet_Assert.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at configSelenium.ConfigSeleniumStart.dotestng(ConfigSeleniumStart.java:1421)
	at configSelenium.ConfigSeleniumStart.main(ConfigSeleniumStart.java:237)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- star -->
        <test-method status="FAIL" signature="star(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Test.DataProviderSet_Assert@41382722]" name="star" duration-ms="0" started-at="2019-04-17T17:16:55Z" data-provider="AssertData" finished-at="2019-04-17T17:16:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[项目信息]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[项目信息]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[项目信息标题断言]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at Test.DataProviderSet_Assert.star(DataProviderSet_Assert.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at configSelenium.ConfigSeleniumStart.dotestng(ConfigSeleniumStart.java:1421)
	at configSelenium.ConfigSeleniumStart.main(ConfigSeleniumStart.java:237)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- star -->
        <test-method status="FAIL" signature="star(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Test.DataProviderSet_Assert@41382722]" name="star" duration-ms="0" started-at="2019-04-17T17:16:55Z" data-provider="AssertData" finished-at="2019-04-17T17:16:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[    添加]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[听]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[添加]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(Unknown Source)
	at Test.DataProviderSet_Assert.star(DataProviderSet_Assert.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at configSelenium.ConfigSeleniumStart.dotestng(ConfigSeleniumStart.java:1421)
	at configSelenium.ConfigSeleniumStart.main(ConfigSeleniumStart.java:237)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- star -->
        <test-method status="PASS" signature="deleteExcel()[pri:0, instance:Test.DataProviderSet_Assert@41382722]" name="deleteExcel" is-config="true" duration-ms="9" started-at="2019-04-17T17:16:55Z" finished-at="2019-04-17T17:16:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteExcel -->
      </class> <!-- Test.DataProviderSet_Assert -->
    </test> <!-- 断言详情查看 -->
  </suite> <!-- 所有首次登记流程-国有建设用地使用权及房屋所有权（单套）-首次登记-assert -->
</testng-results>
